- name: Copy folder or file to server
  hosts: all
  become: yes
  tasks:

    - name: Copy a folder to the server
      ansible.builtin.copy:
        src: /etc/ansible/FILES/python3-build/pexpect-4.9.0-py2.py3-none-any.whl
        dest: /home/ansible/
        owner: root
        group: root
        mode: '0755'
          #recurse: yes

    - name: List the copied file
      ansible.builtin.command: ls -l /home/ansible/pexpect-4.9.0-py2.py3-none-any.whl
      register: file_listing

